version: '3'
services:
  telegram-onedrive:
    container_name: telegram-onedrive
    image: hlf01/telegram-onedrive
    restart: always
    
    # xxxx is the port you want to be reflected
    ports:
      - xxxx:8080

    # volumes:
      # if you have your own ssl files, uncomment and edit these two lines:
      # - /path/to/*.crt:/telegram-onedrive/server/ssl/server.crt
      # - /path/to/*.key:/telegram-onedrive/server/ssl/server.key
      # if you want to save your login session, uncomment this line, no edit needed:
      # - telegram-onedrive-session:/telegram-onedrive/session

    environment:
      - server_uri=$server_uri(must be https, like https://example.com)
      # - reverse_proxy=$reverse_proxy(optional, true or false, default to false)
      - tg_bot_token=$tg_bot_token
      - tg_api_id=$tg_api_id
      - tg_api_hash=$tg_api_hash
      - tg_user_phone=$tg_user_phone(use international format, like +xxyyyyyyyyyyy)
      # - tg_user_password=$tg_user_password(optional, if you have two-step verification enabled)
      # - tg_user_name=$tg_user_name(optional, no @)
      - od_client_id=$od_client_id
      - od_client_secret=$od_client_secret
      - remote_root_path=$remote_root_path(like /Videos/from-telegram)
      # - delete_flag=$delete_flag(optional, true or false, default to false)
    command: python main.py

# if you want to save your login session, uncomment these two lines, no edit needed:
# volumes:
#   telegram-onedrive-session: